project:
  type: book

jupyter: "conda-env-nersa25-py"

execute: 
  freeze: auto
  cache: true

book:

  title: "Spatial: Networks, Interaction, & Econometrics for Migration"
  author: 
    - name: "Elijah Knaap"
      email: eknaap@uci.edu
      affiliation: 
          name: University of California, Irvine
          department: Urban Planning & Public Policy
      orcid: 0000-0001-7520-2238
      url: https://knaaptime.com
      degrees: Ph.D
  date: "7/25/2025"
  chapters:
    - index.qmd
    - notebooks/01_spatial_graphs.qmd
    - notebooks/02_spatial_interaction.qmd
    - notebooks/03_spatial_dependence.qmd
  license: CC BY-NC
  search: true
  repo-url: https://github.com/knaaptime/workshop-nersa25/
  repo-subdir: docs
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin, facebook]
  open-graph: true
  twitter-card: true
  google-analytics: "G-0PG1JNLCXB"
bibliography: nersa25.bib


format:
  html:
    theme: 
      light: 
        - flatly
        - brand
      dark: 
        - darkly
        - brand
    fontsize: 1em
    linkcolor: "#4682B4"
    lightbox: auto
    fig-responsive: true
    fig-format: retina
    toc: true
    citation: true
    google-scholar: true

    code-links: 
      - text: Open in Codespaces
        href: https://codespaces.new/knaaptime/workshop-nersa25
        icon: cloud

